name: CD(continuous deploy)

on:
  push: 
    branches: 
      - staging
      - main

jobs:
  pipeline-cd:
    runs-on: ubuntu-latest    
    steps:

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch